.TH "GNOME-POMODORO" "7"
.SH "NAME"
gnome-pomodoro \(em A time management utility for GNOME
.SH "DESCRIPTION"
.PP
This manual page documents briefly the \fBgnome-pomodoro\fR
application.
.PP
This manual page was written for the \fBDebian\fP distribution
because the original program does not have a manual page.

.PP
\fBgnome-pomodoro\fR is a GNOME utility that helps to manage time
according to Pomodoro Technique. It intends to improve
productivity and focus by taking short breaks.

.PP
Features

 * Countdown timer in the GNOME Shell top panel
 * Screen notifications that can be easily dismissed
 * Hiding other notifications during pomodoro
 * Postponing pomodoro unless there is some activity
 * Option to quickly shorten/lenghten the break
 * Nagging to take a break

.PP
More information about GNOME Pomodoro can be found at
https://github.com/codito/gnome-shell-pomodoro

.SH "AUTHOR"

.PP
\fBgnome-pomodoro\fR has been written by Kamil Prusko <kamilprusko@gmail.com>
with the help of community contributions.

.PP
This manual page was written by Joseph Herlant <herlantj@gmail.com>
for the \fBDebian\fP system (but may be used by others).
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, Version 3 any
later version published by the Free Software Foundation.

.PP
On Debian systems, the complete text of the GNU General Public
License can be found in /usr/share/common-licenses/GPL.
